# Generated by Django 3.1 on 2020-09-17 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perfis', '0001_initial'),
        ('postagem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfis.perfil')),
            ],
            options={
                'verbose_name': 'timeline',
                'verbose_name_plural': 'timelines',
                'db_table': 'TIMELINE',
            },
        ),
        migrations.CreateModel(
            name='TimelinePostagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postagem.postagem')),
                ('timeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeline.timeline')),
            ],
            options={
                'verbose_name': 'postagem da Timeline',
                'verbose_name_plural': 'postagens da Timeline',
                'db_table': 'TIMELINE_POSTAGEM',
            },
        ),
    ]
